# base.yaml 基础样式配置
style:
  auto_caps: false #自動句首大寫:true|false|ascii
  background_dim_amount: 0.5
  candidate_font: han.ttf #候選字型
  candidate_padding: 5 #候選項內邊距
  candidate_spacing: 0.5 #候選間距
  candidate_text_size: 22 #候選字號
  candidate_use_cursor: true #高亮候選項
  candidate_view_height: 28 #候選區高度
  color_scheme: default #配色方案
  comment_font: comment.ttf #編碼提示字型
  comment_height: 12 #編碼提示區高度
  comment_on_top: true #編碼提示在上方或右側
  comment_text_size: 12 #編碼提示字號
  hanb_font: hanb.ttf #擴充字型
  horizontal: true #水平模式
  horizontal_gap: 1 #鍵水平間距
  layout: #懸浮窗口設置
    position: fixed #位置：left|right|left_up|right_up|fixed|bottom_left|bottom_right|top_left|top_right(left、right需要>=Android5.0)
    min_length: 5 #最小詞長
    max_length: 10 #超過字數則換行
    sticky_lines: 0 #固頂行數
    max_entries: 1 #最大詞條數
    all_phrases: false #所有滿足條件的詞語都顯示在窗口
    border: 2 #邊框寬度
    max_width: 230 #最大寬度，超過則自動換行
    max_height: 400 #最大高度
    min_width: 40 #最小寬度
    min_height: 0 #最小高度
    margin_x: 5 #水平邊距
    margin_y: 5 #豎直邊距
    line_spacing: 0 #候选詞的行間距(px)
    line_spacing_multiplier: 1.2 #候选詞的行間距(倍數)
    spacing: 1 #與預編輯或邊緣的距離
    round_corner: 8 #窗口圓角
    alpha: 0xdd #透明度(0-255)
    elevation: 5 #陰影(>=Android5.0)
    background: background.png #顏色或者backgrounds目錄下的圖片文件名
    movable: once #是否可移動窗口，或僅移動一次 true|false|once
  window: #懸浮窗口組件
    - {start: "", move: 'ㄓ ', end: ""}
    - {start: "", composition: "%s", end: "", letter_spacing: 0} #letter_spacing需要>=Android5.0。TODO: 不爲0時，會導致不換行的問題
    - {start: "\n", label: "%s.", candidate: "%s", comment: " %s", end: "", sep: " "}
  key_font: symbol.ttf #鍵盤字型
  key_height: 44 #鍵高
  key_long_text_size: 14 #長標籤字號
  key_text_size: 22 #鍵字號
  key_width: 10.0 #鍵寬，佔螢幕寬的百分比
  keyboards: [.default, letter, number, symbols] #鍵盤配置：自動鍵盤、字母、數字、符號
  label_text_size: 22 #標籤字號
  label_font: label.ttf #編標籤字型
  latin_font: latin.ttf #西文字型
  latin_locale: en_US #西文語言
  locale: zh_TW #預設語言 zh_TW,zh_CN,zh_HK,""
  preview_font: latin.ttf #按鍵提示字型
  preview_height: 60 #按鍵提示高度
  preview_offset: -12 #按鍵提示縱向偏移
  preview_text_size: 40 #按鍵提示字號
  proximity_correction: true #按鍵糾錯
  reset_ascii_mode: false #顯示鍵盤時重置爲中文狀態
  round_corner: 8 #按鍵圓角半徑
  shadow_radius: 0.0 #按鍵陰影半徑
  speech_opencc_config: s2t.json #語音輸入簡繁轉換
  symbol_font: symbol.ttf #符號字型
  symbol_text_size: 10 #符號字號
  text_font: latin.ttf #編碼字型
  #text_height: 22 #編碼區高度
  text_size: 16 #編碼區字號
  vertical_correction: -10
  vertical_gap: 1 #鍵盤行距

fallback_colors:
  candidate_text_color: text_color
  comment_text_color: candidate_text_color
  border_color: back_color
  candidate_separator_color: border_color
  hilited_text_color: text_color
  hilited_back_color: back_color
  hilited_candidate_text_color: hilited_text_color
  hilited_candidate_back_color: hilited_back_color
  hilited_comment_text_color: comment_text_color
  text_back_color: back_color
  hilited_key_back_color: hilited_candidate_back_color
  hilited_key_text_color: hilited_candidate_text_color
  hilited_key_symbol_color: hilited_comment_text_color
  hilited_off_key_back_color: hilited_key_back_color
  hilited_on_key_back_color: hilited_key_back_color
  hilited_off_key_text_color: hilited_key_text_color
  hilited_on_key_text_color: hilited_key_text_color
  key_back_color: back_color
  key_border_color: border_color
  key_text_color: candidate_text_color
  key_symbol_color: comment_text_color
  keyboard_back_color: border_color
  label_color: candidate_text_color
  off_key_back_color: key_back_color
  off_key_text_color: key_text_color
  on_key_back_color: hilited_key_back_color
  on_key_text_color: hilited_key_text_color
  preview_back_color: key_back_color
  preview_text_color: key_text_color
  shadow_color: border_color
